name: scexv 
version: '2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: ScExV is a web platform for the analysis of FLUIDIGM qPCR data. # 79 char long summary
description: |
  SCExV is a complex tool for the analysis of qPCR data and especially equiped for the FLUIDIGM Biomark platform.  The version 2 of the software has gained several analysis options like the MDS function DDRTree or randome forest clustering of the data.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  stefanslibs:
    plugin: make
    stage-packages:
        - libclass-dbi-mysql-perl
        - libclass-dbi-perl
        - libdate-simple-perl
        - libdatetime-format-mysql-perl
        - libdigest-perl-md5-perl
        - libfile-copy-recursive-perl
        - libfile-homedir-perl
        - libgd-perl
        - libgd-svg-perl
        - libinline-c-perl
        - libnumber-format-perl
        - libstatistics-descriptive-perl
        - libsvg-perl
        - libxml-simple-perl
        - pdl
    prepare: |
         sudo apt-get install --yes pdl libclass-dbi-mysql-perl libdatetime-format-mysql-perl libdigest-perl-md5-perl libstatistics-descriptive-perl libdate-simple-perl libnumber-format-perl libgd-perl libgd-svg-perl libsvg-perl libinline-c-perl libfile-copy-recursive-perl libfile-homedir-perl libclass-dbi-perl libxml-simple-perl
    source: https://github.com/stela2502/Stefans_Lib_Esentials.git
  rfclust:
    plugin: make
    stage-packages:
        - apt-transport-https
        - gfortran
        - libatlas-base-dev
        - libblas-dev
        - libbz2-dev
        - libcurl4-gnutls-dev
        - libgit2-dev
        - liblapack-dev
        - liblzma-dev
        - libpcre3
        - libpcre3-dev
        - libssl-dev
        - libx32quadmath0
        - r-base
        - r-cran-cluster
        - r-cran-hmisc
        - r-cran-mass
        - r-cran-randomforest
        - r-cran-rcurl
        - r-cran-survival
        - software-properties-common
        - zlib1g-dev
    prepare: |
      sudo apt install --yes software-properties-common apt-transport-https
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
      sudo apt-get update
      sudo apt-get install --yes r-base r-cran-randomforest r-cran-survival r-cran-cluster r-cran-hmisc r-cran-mass r-cran-rcurl libcurl4-gnutls-dev libgit2-dev zlib1g-dev libssl-dev gfortran libx32quadmath0 libblas-dev liblapack-dev libpcre3 libpcre3-dev libatlas-base-dev liblzma-dev libbz2-dev 
    source: https://github.com/stela2502/RFclust.SGE.git
  rscexv:
    plugin: make
    after: [rfclust]
    stage-packages:
      - r-cran-rgl
      - libpng16-dev
      - libgl1-mesa-dev
      - libx11-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
    prepare: |
      sudo apt-get install --yes r-cran-rgl libpng16-dev libgl1-mesa-dev libx11-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
    source: https://github.com/stela2502/Rscexv.git
  zifa:
    plugin: python
    prepare: |
         sudo apt install --yes python-pip
         export LC_ALL="en_US.UTF-8"
         export LC_CTYPE="en_US.UTF-8"
         sudo dpkg-reconfigure locales
    source: https://github.com/epierson9/ZIFA.git
  scexv:
    after: [stefanslibs]
    plugin: make
    stage-packages:
      - cpanminus
      - dos2unix
      - libcatalyst-controller-actionrole-perl
      - libcatalyst-controller-formbuilder-perl
      - libcatalyst-modules-extra-perl
      - libcatalyst-modules-perl
      - libcatalyst-perl
      - libcatalyst-plugin-authentication-perl
      - libcatalyst-plugin-configloader-perl
      - libcatalyst-plugin-session-perl
      - libcatalyst-plugin-session-state-cookie-perl
      - libcatalyst-plugin-session-store-file-perl
      - libcatalyst-plugin-stacktrace-perl
      - libcgi-fast-perl
      - libclass-load-perl
      - libclass-load-xs-perl
      - libconfig-general-perl
      - libcpanplus-perl
      - libdata-dmp-perl
      - libdatetime-perl
      - libfile-find-rule-perl
      - libfile-slurp-perl
      - libfile-type-perl
      - libfindbin-libs-perl
      - libhttp-request-params-perl
      - libimport-into-perl
      - libmime-lite-perl
      - libmime-types-perl
      - libmodule-build-perl
      - libmodule-runtime-perl
      - libmoose-perl
      - libmoosex-attribute-chained-perl
      - libmoosex-types-common-perl
      - libmoosex-types-path-class-perl
      - libmro-compat-perl
      - libnamespace-autoclean-perl
      - libpackage-stash-perl 
      - libpackage-stash-xs-perl 
      - libplack-middleware-file-sass-perl
      - libplack-perl 
      - librecommended-perl 
      - libsub-exporter-perl 
      - libtest-exception-perl 
      - libtest-fatal-perl 
      - libtest-most-perl 
      - libtest-useallmodules-perl 
      - liburi-perl 
      - libyaml-perl
      - nginx
    prepare: |
      sudo apt install cpanminus libmoose-perl libplack-perl libcatalyst-perl nginx libplack-middleware-file-sass-perl
      sudo apt-get install --yes dos2unix cpanminus libcatalyst-controller-actionrole-perl libcatalyst-controller-formbuilder-perl libcatalyst-modules-extra-perl libcatalyst-modules-perl libcatalyst-perl libcatalyst-plugin-authentication-perl libcatalyst-plugin-configloader-perl libcatalyst-plugin-session-perl libcatalyst-plugin-session-state-cookie-perl libcatalyst-plugin-session-store-file-perl libcatalyst-plugin-stacktrace-perl libcgi-fast-perl libclass-load-perl libclass-load-xs-perl libcpanplus-perl libconfig-general-perl libdatetime-perl libdata-dmp-perl libfile-slurp-perl libfile-type-perl libfile-find-rule-perl libfindbin-libs-perl libhttp-request-params-perl libimport-into-perl libmime-lite-perl libmime-types-perl libmodule-build-perl libmodule-runtime-perl libmoose-perl libmoosex-attribute-chained-perl libmoosex-types-common-perl libmoosex-types-path-class-perl libmro-compat-perl libnamespace-autoclean-perl libpackage-stash-perl libpackage-stash-xs-perl libplack-perl librecommended-perl libsub-exporter-perl libtest-exception-perl libtest-fatal-perl libtest-most-perl libtest-useallmodules-perl liburi-perl libyaml-perl
      cpanm Sub::Uplevel 
      cpanm Test::Fatal
      cpanm Pod::Coverage
      cpanm Data::OptList
      cpanm Test::Exception
      cpanm Class::Load
      cpanm namespace::autoclean
      cpanm Catalyst::Action::REST
      cpanm Catalyst::Plugin::FormBuilder
      cpanm HTTP::Request
      cpanm Moose
      cpanm Catalyst::Runtime
      apt-get install --yes dos2unix
      ( cd SCExV && perl Makefile.PL --defaultdeps )
    source: https://github.com/stela2502/SCExV.git
    install: |
      rm $SNAPCRAFT_PART_INSTALL/usr/local/lib/x86_64-linux-gnu/perl/5.22.1/perllocal.pod
      mkdir -p $SNAPCRAFT_PART_INSTALL/SCExV/2_0/
      perl -I $SNAPCRAFT_PART_INSTALL/../../stefanslibs/build/Stefans_Libs_Essentials/lib -I $SNAPCRAFT_PART_INSTALL/../build/SCExV/lib $SNAPCRAFT_PART_INSTALL/../build/SCExV/script/install.pl -install_path $SNAPCRAFT_PART_INSTALL/SCExV/2_0/ -options randomForest 1 ncore 2 -server_user www-data
      perl -I $SNAPCRAFT_PART_INSTALL/../../stefanslibs/build/Stefans_Libs_Essentials/lib $SNAPCRAFT_PART_INSTALL/../../stefanslibs/build/Stefans_Libs_Essentials/bin/code_refractor.pl -path $SNAPCRAFT_PART_INSTALL/SCExV/2_0/ -match '/home/stela2502/SCExV_snap/parts/scexv/install/' -replace '/'
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/nginx/sites-available/
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/nginx/sites-enabled/
      cp $SNAPCRAFT_PART_INSTALL/SCExV/2_0/SCExV.nginx $SNAPCRAFT_PART_INSTALL/etc/nginx/sites-available/SCExV_2_0
      cp $SNAPCRAFT_PART_INSTALL/SCExV/2_0/SCExV.nginx $SNAPCRAFT_PART_INSTALL/etc/nginx/sites-enabled/SCExV_2_0
    filesets:
      nginx:
       - etc/nginx/sites-enabled/*
       - etc/nginx/sites-available/*
      scexv:
       - SCExV/2_0/* 
    stage:
      - $nginx
      - $scexv
    prime:
      - $nginx
      - $scexv
apps:
  scexv2:
    command: SCExV/2_0/SCExV.fastcgi.initd start
    stop-command: SCExV/2_0/SCExV.fastcgi.initd stop
    daemon: forking
  nginx:
    command: service nginx start
    stop-command: service nginx stop
    daemon: forking
#    listen-stream: /SCExV/2_0/SCExV.socket
#    socket: true


#services:
#  nginx:
#    caps:
#     - networking
#     - network-service
#    syscalls:
#     - chown
#     - chown32
#     - close
#     - setgid
#    start: "./sbin/nginx"
#    security-template: unconfined      

